### ISSUE TITLE
Merged citations aren't sorted in increasing order

### ISSUE THREAD

**Issue by Enivex** [typst/hayagriva#115]
### Description

At least when using the IEEE style, merged citations are not sorted in increasing order, unless that happens to be the first time they are cited. This means one might end up with something ugly like [48], [49], [35], [50] instead of the more compact [35], [48]-[50].

### Typst version

- [X] I am using the latest version of Typst

**Comment by jclederman** [comment]
Looks like sorting citations by citation number has not been implemented yet. The key code is in csl/sort.rs:
```
pub fn sort<T: EntryLike>(
        &self,
        cites: &mut [CitationItem<T>],
        sort: Option<&Sort>,
        term_locale: Option<&LocaleCode>,
    ) {
        if let Some(sort) = sort {
            cites.sort_by(|a, b| {
                let mut ordering = Ordering::Equal;
                for key in &sort.keys {
                    ordering = self.cmp_entries(a, 0, b, 0, key, term_locale);
                    if ordering != Ordering::Equal {
                        break;
                    }
                }
                ordering
            });
        }
    }
```
cmp_entries is fed 0's for the citation numbers, rather than collecting them from the items. Item sorting within a citation never appears to happen within BibliographyDriver::finish, nor could it using the current sort function. I imagine sort may need to be adjusted to wire the citation numbers in after they are generated with the citation_number closure.
